### ISSUE TITLE
Kerbmun's surface is pitch-black/grayscale close up

### ISSUE THREAD

**Issue by Lithobraker** [GregroxMun/Whirligig-World#10]
I have no clue why this happens, but for some reason the colors of Kerbmun's surface are broken in close-range. Everything looks fine from the Tracking Station and space, but up close it's pitch black, almost as if the procedural coloring is broken- but only up close.
Note that surface textures do appear to be working. I don't really know how procedural colors work, but it almost looks as though the game is coloring the ground using the heightmap.

Confirmed as broken on a 100% stock install save for the mods that are absolutely necessary to run Whirligig World. Bug occurs even if Mesbin is the home world.

Pictures below, including my GameData folder:
![gamedata](https://user-images.githubusercontent.com/6070905/220259247-4772e2a8-5fd8-4332-9c92-2f330396575f.png)
![screenshot8](https://user-images.githubusercontent.com/6070905/220259270-7da2f294-cb74-495f-a1af-2012d14f38e0.png)
![screenshot9](https://user-images.githubusercontent.com/6070905/220259276-6b86d3fc-16fb-4d11-a708-e7262918bd66.png)
![screenshot10](https://user-images.githubusercontent.com/6070905/220259285-a2b5ce15-7235-4461-bf92-96fd66e870c2.png)

**Comment by Lithobraker** [comment]
Did a little more research, and discovered this odd effect.
It would seem that, from scaledspace, Kerbmun has no heightmap, but the color works fine. However, when I zoom in, the heightmap appears, but the colors break.
Very odd.
![screenshot13](https://user-images.githubusercontent.com/6070905/220269625-fca0989f-110c-4f29-9f6f-8edf496e4de0.png)
![screenshot15](https://user-images.githubusercontent.com/6070905/220269644-9556b843-f98f-4bc4-b87a-c477b3240921.png)

**Comment by Lithobraker** [comment]
OhioBob and I(well really it was all them, I just tested things) on the Kopernicus discord have located the source of both issues.
The flat scaledspace model is caused by this line:
`sphericalModel = True`
Setting it to false will cause the heightmap to appear in scaledspace.
The grayscale surface problem is caused by this line in the Kopernicus config:
`EnableColorFix = True`
Apparently, using LandControl to color terrain causes some issues, and Kopernicus automatically sets all the colors to 0,0,0,0.  Setting this value to false fixes Kerbmun.
According to OhioBob, the color fix thing was a recent change, probably after the most recent Whirligig World update. A simple band-aid solution could be to instruct players to set EnableColorFix to false in their Kopernicus config.

**Comment by Lithobraker** [comment]
As a result of a conversation on the Kopernicus discord, it seems R-T-B has discovered that the color fix is no longer necessary, and it's been removed from the latest release. I tested that release and it works with Kerbmun right out of the box, though I'd imagine the flat scaledspace model is still a thing.

**Comment by WhirligigGirl** [comment]
flat scaledspace model is intentional. Due to the low resolution of the scaledspace mesh, it looks bad when used with the stock atmosphere rim. IIRC, Kerbmun should have a nonspherical scaledspace mesh when scatterer is installed.

**Comment by Lithobraker** [comment]
> flat scaledspace model is intentional. Due to the low resolution of the scaledspace mesh, it looks bad when used with the stock atmosphere rim. IIRC, Kerbmun should have a nonspherical scaledspace mesh when scatterer is installed.

Okay, thanks for the clarification!
